'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Check, LockKeyhole, Minus, PackageCheck, Plus, ShieldCheck, Truck } from 'lucide-react';
import { Brand } from '@/components/brand';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { PRODUCT, formatNpr } from '@/lib/product';

type Fields={fullName:string;phone:string;email:string;location:string;notes:string};
const empty:Fields={fullName:'',phone:'',email:'',location:'',notes:''};

export function CheckoutForm(){
 const router=useRouter(); const [fields,setFields]=useState(empty); const [quantity,setQuantity]=useState(1); const [errors,setErrors]=useState<Record<string,string>>({}); const [submitting,setSubmitting]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{const q=Number(new URLSearchParams(window.location.search).get('quantity')); if(Number.isInteger(q)&&q>=1&&q<=10)setQuantity(q)},[]);
 const update=(key:keyof Fields,value:string)=>{setFields(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:''}));};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(submitting)return;setSubmitting(true);setMessage('');setErrors({});try{const response=await fetch('/api/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,productName:PRODUCT.name,quantity,unitPrice:PRODUCT.price,totalPrice:PRODUCT.price*quantity})});const result=await response.json() as {success:boolean;error?:string;fields?:Record<string,string>;orderId?:string};if(!response.ok||!result.success){setErrors(result.fields||{});throw new Error(result.error||'We could not submit your order. Please try again.');}const params=new URLSearchParams({orderId:result.orderId!,product:PRODUCT.name,quantity:String(quantity),total:String(PRODUCT.price*quantity)});router.push(`/thank-you?${params}`);}catch(error){setMessage(error instanceof Error?error.message:'We could not submit your order. Please try again.');setSubmitting(false);}};
 const fieldClass='h-12 rounded-xl border-white/10 bg-white/[0.035] px-4 text-white placeholder:text-stone-600 focus-visible:border-gold';
 return <main className="min-h-screen bg-[#090908] text-white"><header className="border-b border-white/8"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Brand /><Link href="/" className="flex items-center gap-2 text-xs uppercase tracking-widest text-stone-400 hover:text-gold"><ArrowLeft className="size-4" />Continue shopping</Link></div></header><div className="mx-auto grid max-w-6xl gap-10 px-5 py-12 sm:px-8 sm:py-16 lg:grid-cols-[1.1fr_.9fr] lg:gap-16">
  <section><p className="eyebrow">Secure checkout</p><h1 className="font-serif text-4xl sm:text-5xl">Where should we deliver your guitar?</h1><p className="mt-4 max-w-xl text-sm leading-6 text-stone-400">Enter your details below. No online payment is required—we’ll call to confirm before dispatch.</p><form onSubmit={submit} className="mt-10 space-y-5" noValidate><div className="grid gap-5 sm:grid-cols-2"><Field label="Full Name" error={errors.fullName}><Input value={fields.fullName} onChange={e=>update('fullName',e.target.value)} placeholder="Your full name" autoComplete="name" className={fieldClass} aria-invalid={!!errors.fullName}/></Field><Field label="Phone Number" error={errors.phone}><Input value={fields.phone} onChange={e=>update('phone',e.target.value)} placeholder="98XXXXXXXX" inputMode="tel" autoComplete="tel" className={fieldClass} aria-invalid={!!errors.phone}/></Field></div><Field label="Email Address" error={errors.email}><Input type="email" value={fields.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com" autoComplete="email" className={fieldClass} aria-invalid={!!errors.email}/></Field><Field label="Exact Location" error={errors.location}><Textarea value={fields.location} onChange={e=>update('location',e.target.value)} placeholder="Kindly share your exact location" autoComplete="street-address" className="min-h-28 rounded-xl border-white/10 bg-white/[0.035] px-4 py-3 text-white placeholder:text-stone-600 focus-visible:border-gold" aria-invalid={!!errors.location}/></Field><Field label="Order Notes (optional)"><Textarea value={fields.notes} onChange={e=>update('notes',e.target.value)} placeholder="Landmark, preferred call time, or anything else" className="min-h-20 rounded-xl border-white/10 bg-white/[0.035] px-4 py-3 text-white placeholder:text-stone-600 focus-visible:border-gold" maxLength={500}/></Field>{message&&<div role="alert" className="rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-sm text-red-200">{message}</div>}<button type="submit" disabled={submitting} className="flex w-full items-center justify-center gap-3 rounded-full bg-gold px-8 py-4 text-sm font-bold uppercase tracking-[0.16em] text-black transition hover:bg-[#e1bc73] disabled:cursor-not-allowed disabled:opacity-60">{submitting?<><span className="size-4 animate-spin rounded-full border-2 border-black/30 border-t-black" />Submitting Order...</>:<><LockKeyhole className="size-4" />Order Now · {formatNpr(PRODUCT.price*quantity)}</>}</button><p className="text-center text-xs text-stone-500">By ordering, you agree to receive a confirmation call from KRISTONE GUITARS.</p></form></section>
  <aside className="lg:sticky lg:top-8 lg:self-start"><div className="overflow-hidden rounded-3xl border border-white/10 bg-[#12110f]"><div className="aspect-[16/10] overflow-hidden bg-black"><img src="/images/kristone-package.png" alt="Kristone acoustic guitar with protective case" className="h-full w-full object-cover object-[center_68%]" /></div><div className="p-6 sm:p-8"><p className="text-[10px] uppercase tracking-[0.2em] text-gold">Your order</p><h2 className="mt-2 font-serif text-2xl">{PRODUCT.name}</h2><div className="mt-6 flex items-center justify-between border-y border-white/8 py-5"><span className="text-sm text-stone-400">Quantity</span><div className="flex items-center rounded-full border border-white/15"><button type="button" onClick={()=>setQuantity(Math.max(1,quantity-1))} className="p-2.5" aria-label="Decrease quantity"><Minus className="size-4" /></button><span className="min-w-9 text-center text-sm font-semibold">{quantity}</span><button type="button" onClick={()=>setQuantity(Math.min(10,quantity+1))} className="p-2.5" aria-label="Increase quantity"><Plus className="size-4" /></button></div></div><Summary label="Price per piece" value={formatNpr(PRODUCT.price)} /><Summary label="Delivery" value="FREE" gold /><div className="mt-4 flex items-end justify-between border-t border-white/8 pt-5"><span className="font-semibold">Total</span><span className="font-serif text-3xl text-gold">{formatNpr(PRODUCT.price*quantity)}</span></div><div className="mt-7 space-y-3">{[[Truck,'Free delivery across Nepal'],[ShieldCheck,'Cash on Delivery'],[PackageCheck,'Phone confirmation before dispatch']].map(([Icon,text])=><div key={String(text)} className="flex items-center gap-3 text-xs text-stone-400"><Icon className="size-4 text-gold" /><span>{String(text)}</span></div>)}</div></div></div></aside>
 </div></main>;
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[0.12em] text-stone-300">{label}</span>{children}{error&&<span className="mt-1.5 block text-xs text-red-300">{error}</span>}</label>}
function Summary({label,value,gold=false}:{label:string;value:string;gold?:boolean}){return <div className="mt-4 flex justify-between text-sm"><span className="text-stone-500">{label}</span><span className={gold?'font-bold text-gold':'text-stone-200'}>{value}</span></div>}
